# Generated by Django 4.2 on 2023-04-21 18:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 21, 15, 37, 6, 99918)),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='frete',
            field=models.FloatField(blank=True, max_length=20, null=True),
        ),
    ]
