# Generated by Django 4.2 on 2023-04-20 21:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_alter_pedido_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logo',
            name='backgroud',
            field=models.ImageField(blank=True, null=True, upload_to='logos_img'),
        ),
        migrations.AlterField(
            model_name='logo',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos_img'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 20, 18, 13, 0, 885701)),
        ),
    ]
