name: Django CI

on:
  push:
    branches: [ "saas" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r libs.txt
      
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
        EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}
        BANCO: ${{ secrets.BANCO }}
        USER: ${{ secrets.BANCO_USER }}
        PASSWORD: ${{ secrets.BANCO_PASSWORD }}
        HOST: ${{ secrets.BANCO_HOST }}



    - name: Run Tests
      run: |
        python manage.py test && ls -la
